### ISSUE TITLE
TODO - URGENT

### ISSUE THREAD

**Issue by Saydemr** [Saydemr/EPPuGNN#35]
- [x] BIOGRID data needs to be updated to v211 before anything else!!!
- [x] StandardScaler needs to be used for each feature group. (separately?? after merge??)
- [x] K-fold needs to be changed with stratified k-fold in the XGBoost classifier.
- [x] Centrality method results to be updated.
- [x] Json dumps need to be checked for possible mapping errors for homo sapiens.
- [x] sage_boost model needs to be automated and the parameters of this model need to be optimized.
- [x] Random walk generation must be tested in BLEND for different p & q parameters.
- [x] New data to be fed to GRAND & BLEND.
- [x] Different SMOTE techniques and results must be compared.

**Comment by Saydemr** [comment]
Done!
